
type keyType = {
	mongoURI: string;
	EMAIL_API_KEY: string;
	JWT_SECRET: string;
	ADMIN_PASS: string;
	ADMIN_USER: string;
	AWS_PARTNER_PHOTO_ACCESS_KEY: string;
	AWS_PARTNER_PHOTO_SECRET_ACCESS_KEY: string;
	AWS_PARTNER_PHOTO_LINK: string;
	ADMIN_BASIC_DEV_STRING: string;
	ADMIN_BASIC_DEV_KEY: string;
	MONGO_URI_PROD: string;
	GOOGLE_API_KEY: string;
	CRYPTO_PASSWORD: string;
	CRYPTO_SECOND: string;
	NEST_PAY_CLIENT_ID: string;
	NEST_PAY_RANDOM: string;
	NEST_PAY_STORE_KEY: string;
	VIBER_BOT_TOKEN: string;
}

const keys: keyType = {
	mongoURI: process.env.MONGO_URI,
	EMAIL_API_KEY: process.env.EMAIL_API_KEY,
	JWT_SECRET: process.env.JWT_SECRET,
	ADMIN_PASS: process.env.ADMIN_PASS,
	ADMIN_USER: process.env.ADMIN_USER,
	AWS_PARTNER_PHOTO_ACCESS_KEY: process.env.AWS_PARTNER_PHOTO_ACCESS_KEY,
	AWS_PARTNER_PHOTO_SECRET_ACCESS_KEY: process.env.AWS_PARTNER_PHOTO_SECRET_ACCESS_KEY,
	AWS_PARTNER_PHOTO_LINK: process.env.AWS_PARTNER_PHOTO_LINK,
	ADMIN_BASIC_DEV_STRING: process.env.ADMIN_BASIC_DEV_STRING,
	ADMIN_BASIC_DEV_KEY: process.env.ADMIN_BASIC_DEV_KEY,
	MONGO_URI_PROD: process.env.MONGO_URI_PROD,
	GOOGLE_API_KEY: process.env.GOOGLE_API_KEY,
	CRYPTO_PASSWORD: process.env.CRYPTO_PASSWORD,
	CRYPTO_SECOND: process.env.CRYPTO_SECOND,
	NEST_PAY_CLIENT_ID: process.env.NEST_PAY_CLIENT_ID,
	NEST_PAY_RANDOM: process.env.NEST_PAY_RANDOM,
	NEST_PAY_STORE_KEY: process.env.NEST_PAY_STORE_KEY,
	VIBER_BOT_TOKEN: process.env.VIBER_BOT_TOKEN
}

export default keys;