defaults: &defaults
    docker:
        - image: circleci/node:10.16.3
    working_directory: ~/tmp/circlci-now

version: 2.1
orbs:
  cypress: cypress-io/cypress@1.10.0
jobs:
    checkout:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                at: ~/tmp/circlci-now
            - restore_cache:
                keys:
                    - npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
                    - npm-cache-{{ .Branch }}
                    - npm-cache-
            - run:
                name: NPM Install
                command: npm install
            - save_cache:
                key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - persist_to_workspace:
                root: .
                paths: .
    
workflows:
    version: 2
    test-deploy-purge:
        jobs:
            - checkout
            - cypress/run:
                executor: cypress/base-8
                start: npm run dev
                wait-on: 'http://localhost:3000'
                requires:
                    - checkout
            - deploy:
                requires:
                    - cypress/run