const apiHandlingErrors = ['DELETE_RESERVATION_ERROR', 'GET_RESERVATIONS_ONDATE_ERROR', 'CONFIRM_RESERVATION_ERROR', 'CONFIRM_CATERING_ERROR', 'GET_RESERVATIONS_FOR_USER_ERROR', 'CANCEL_RESERVATION_ERROR', 'USER_SAVE_RESRVATION_ERROR', 'PARTNER_GET_RESERVATIONS_ERROR', 'PARTNER_SAVE_RESERVATION_ERROR', 'PARTNER_GET_RESERVATION_TERMS_ERROR', 'PARTNER_PROFILE_GET_ERROR', 'PARTNER_DECORATION_UPDATE_ERROR', 'PARTNER_CATERING_UPDATE_ERROR', 'PARTNER_OFFER_UPDATE_ERROR', 'PARTNER_GENERAL_UPDATE_ERROR', 'PARTNER_MULTIPLE_GET_ERROR', 'PARTNER_GET_ERROR'];

const apiErrorHandlingMiddleware = ({ getState, dispatch }) => next => action => {
  if (apiHandlingErrors.indexOf(action.type) !== -1) {
    next({
      type: 'ERROR_HANDLER',
      payload: true,
    })
  }else{
    next(action);
  }
}

export default apiErrorHandlingMiddleware;