name: CI

on: 
  push:
    branches:
     -stage

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Stage has a push!
